// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSOpen.Infrastructure.Persistence;

#nullable disable

namespace POSOpen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosOpenDbContext))]
    partial class PosOpenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("POSOpen.Domain.Entities.AdmissionCheckInRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("CompletedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_status");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmation_code");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("receipt_reference");

                    b.Property<string>("SettlementDeferredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("settlement_deferred_at_utc");

                    b.Property<int>("SettlementStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("settlement_status");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_admission_check_in_records_operation_id");

                    b.HasIndex("FamilyId", "CompletedAtUtc")
                        .HasDatabaseName("ix_admission_check_in_records_family_completed");

                    b.ToTable("admission_check_in_records", (string)null);
                });

                modelBuilder.Entity("POSOpen.Domain.Entities.CartLineItem", b =>
                    {
                        b.Property<Guid>("Id")
                            .HasColumnType("TEXT")
                            .HasColumnName("id");

                        b.Property<Guid>("CartSessionId")
                            .HasColumnType("TEXT")
                            .HasColumnName("cart_session_id");

                        b.Property<string>("CurrencyCode")
                            .IsRequired()
                            .HasMaxLength(3)
                            .HasColumnType("TEXT")
                            .HasColumnName("currency_code");

                        b.Property<string>("CreatedAtUtc")
                            .IsRequired()
                            .HasColumnType("TEXT")
                            .HasColumnName("created_at_utc");

                        b.Property<string>("Description")
                            .IsRequired()
                            .HasMaxLength(200)
                            .HasColumnType("TEXT")
                            .HasColumnName("description");

                        b.Property<int>("FulfillmentContext")
                            .HasColumnType("INTEGER")
                            .HasColumnName("fulfillment_context");

                        b.Property<int>("Quantity")
                            .HasColumnType("INTEGER")
                            .HasColumnName("quantity");

                        b.Property<Guid?>("ReferenceId")
                            .HasColumnType("TEXT")
                            .HasColumnName("reference_id");

                        b.Property<long>("UnitAmountCents")
                            .HasColumnType("INTEGER")
                            .HasColumnName("unit_amount_cents");

                        b.Property<string>("UpdatedAtUtc")
                            .IsRequired()
                            .HasColumnType("TEXT")
                            .HasColumnName("updated_at_utc");

                        b.HasKey("Id");

                        b.HasIndex("CartSessionId")
                            .HasDatabaseName("ix_cart_line_items_cart_session_id");

                        b.ToTable("cart_line_items", (string)null);
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.CartSession", b =>
                    {
                        b.Property<Guid>("Id")
                            .HasColumnType("TEXT")
                            .HasColumnName("id");

                        b.Property<string>("CreatedAtUtc")
                            .IsRequired()
                            .HasColumnType("TEXT")
                            .HasColumnName("created_at_utc");

                        b.Property<Guid?>("FamilyId")
                            .HasColumnType("TEXT")
                            .HasColumnName("family_id");

                        b.Property<Guid>("StaffId")
                            .HasColumnType("TEXT")
                            .HasColumnName("staff_id");

                        b.Property<int>("Status")
                            .HasColumnType("INTEGER")
                            .HasColumnName("cart_status");

                        b.Property<string>("UpdatedAtUtc")
                            .IsRequired()
                            .HasColumnType("TEXT")
                            .HasColumnName("updated_at_utc");

                        b.HasKey("Id");

                        b.HasIndex("StaffId", "Status")
                            .HasDatabaseName("ix_cart_sessions_staff_status");

                        b.HasIndex("StaffId")
                            .IsUnique()
                            .HasDatabaseName("ux_cart_sessions_staff_open")
                            .HasFilter("cart_status = 0");

                        b.ToTable("cart_sessions", (string)null);
                    });

            modelBuilder.Entity("POSOpen.Domain.Entities.CheckoutPaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authorization_status");

                    b.Property<Guid>("CartSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_session_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostic_code");

                    b.Property<string>("OccurredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ProcessorReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("processor_reference");

                    b.HasKey("Id");

                    b.HasIndex("CartSessionId")
                        .HasDatabaseName("ix_checkout_payment_attempts_cart_session_id");

                    b.ToTable("checkout_payment_attempts", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.FamilyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_staff_id");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryContactFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("PrimaryContactLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("ScanToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_token");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WaiverCompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("waiver_completed_at_utc");

                    b.Property<int>("WaiverStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("waiver_status");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_family_profiles_phone");

                    b.HasIndex("PrimaryContactLastName")
                        .HasDatabaseName("ix_family_profiles_last_name");

                    b.HasIndex("ScanToken")
                        .HasDatabaseName("ix_family_profiles_scan_token");

                    b.ToTable("family_profiles", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.OperationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("AggregateId", "RecordedUtc");

                    b.ToTable("OperationLogEntries", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnqueuedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("PublishedUtc", "EnqueuedUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.PartyBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("PartyDateUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("party_date_utc");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("slot_id");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("package_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("BookedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("booked_at_utc");

                    b.Property<long?>("DepositAmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deposit_amount_cents");

                    b.Property<string>("DepositCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("deposit_currency");

                    b.Property<string>("DepositCommittedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deposit_committed_at_utc");

                    b.Property<int>("DepositCommitmentStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deposit_commitment_status");

                    b.Property<Guid?>("DepositCommitmentOperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("deposit_commitment_operation_id");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("AssignedRoomId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_room_id");

                    b.Property<string>("RoomAssignedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("room_assigned_at_utc");

                    b.Property<Guid?>("RoomAssignmentOperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("room_assignment_operation_id");

                    b.Property<Guid?>("LastAddOnUpdateOperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_add_on_update_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_party_bookings_operation_id");

                    b.HasIndex("DepositCommitmentOperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_bookings_deposit_commitment_operation_id")
                        .HasFilter("deposit_commitment_operation_id IS NOT NULL");

                    b.HasIndex("PartyDateUtc", "SlotId", "Status")
                        .HasDatabaseName("ix_party_bookings_party_date_slot_status");

                    b.HasIndex("Status", "PartyDateUtc")
                        .HasDatabaseName("ix_party_bookings_status_party_date");

                    b.HasIndex("PartyDateUtc", "SlotId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_bookings_active_slot")
                        .HasFilter("status <> 2");

b.HasIndex("AssignedRoomId", "PartyDateUtc", "SlotId")
						.IsUnique()
						.HasDatabaseName("ux_party_bookings_room_date_slot")
						.HasFilter("assigned_room_id IS NOT NULL AND status <> 2");

                    b.ToTable("party_bookings", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.PartyBookingAddOnSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_id");

                    b.Property<int>("AddOnType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("add_on_type");

                    b.Property<string>("OptionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("option_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("SelectedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_at_utc");

                    b.Property<Guid>("SelectionOperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("selection_operation_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_party_booking_add_on_sel_booking_id");

                    b.HasIndex("SelectionOperationId")
                        .HasDatabaseName("ix_party_booking_add_on_sel_operation_id");

                    b.ToTable("party_booking_add_on_selections", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.ReceiptMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostic_code");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_count");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<string>("PrintedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("printed_at_utc");

                    b.Property<int>("PrintStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("print_status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_metadata_operation_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_receipt_metadata_transaction_id");

                    b.ToTable("receipt_metadata", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.RefundRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("ActorStaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_staff_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("CartSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_session_id");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<int>("Path")
                        .HasColumnType("INTEGER")
                        .HasColumnName("path");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CartSessionId")
                        .HasDatabaseName("ix_refund_records_cart_session_id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_refund_records_operation_id");

                    b.ToTable("refund_records", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.StaffAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_staff_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("LockedUntilUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_salt");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByStaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_staff_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_accounts_email");

                    b.ToTable("staff_accounts", (string)null);
                });

            modelBuilder.Entity("POSOpen.Domain.Entities.TransactionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OperationData")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_data");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_transaction_operations_operation_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_operations_transaction_id");

                    b.ToTable("transaction_operations", (string)null);
                });
#pragma warning restore 612, 618

                modelBuilder.Entity("POSOpen.Domain.Entities.CartLineItem", b =>
                    {
                        b.HasOne("POSOpen.Domain.Entities.CartSession", null)
                            .WithMany("LineItems")
                            .HasForeignKey("CartSessionId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.CheckoutPaymentAttempt", b =>
                    {
                        b.HasOne("POSOpen.Domain.Entities.CartSession", null)
                            .WithMany()
                            .HasForeignKey("CartSessionId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.RefundRecord", b =>
                    {
                        b.HasOne("POSOpen.Domain.Entities.CartSession", null)
                            .WithMany()
                            .HasForeignKey("CartSessionId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.PartyBookingAddOnSelection", b =>
                    {
                        b.HasOne("POSOpen.Domain.Entities.PartyBooking", "Booking")
                            .WithMany("AddOnSelections")
                            .HasForeignKey("BookingId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();

                        b.Navigation("Booking");
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.CartSession", b =>
                    {
                        b.Navigation("LineItems");
                    });

                modelBuilder.Entity("POSOpen.Domain.Entities.PartyBooking", b =>
                    {
                        b.Navigation("AddOnSelections");
                    });
        }
    }
}
